Switch to System.Text.Json
maxmind/GeoIP2-dotnet pull request #142
Opened 2020-11-13 23:38 UTC by oschwald

2020-11-16 18:37 UTC, horgh requested changes
Nice to drop dependencies!

2020-11-16 18:37 UTC, horgh commented on releasenotes.md
> +  `Newtonsoft.Json` is no longer support for serialization or deserialization.
"supported"

2020-11-17 16:19 UTC, oschwald commented on releasenotes.md
> +  `Newtonsoft.Json` is no longer support for serialization or deserialization.
Thanks. I force pushed a fix.

2020-11-17 16:36 UTC, horgh approved these changes

2020-11-17 16:36 UTC, merged